// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockHealthSystem.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MockHealthSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227154757_AddAuthSettings")]
    partial class AddAuthSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Allergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.AuthSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessTokenLifetimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("BearerToken")
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OAuthClientId")
                        .HasColumnType("text");

                    b.Property<string>("OAuthClientSecret")
                        .HasColumnType("text");

                    b.Property<int>("RefreshTokenLifetimeDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuthSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessTokenLifetimeMinutes = 60,
                            Mode = "None",
                            RefreshTokenLifetimeDays = 30
                        });
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.AuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("AuthTokens");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icd10Code")
                        .HasColumnType("text");

                    b.Property<string>("Icd9Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.ConditionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConditionTypes");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Immunization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Immunizations");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.ImmunizationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImmunizationTypes");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.MedicationRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedicationRoutes");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<string>("Address3")
                        .HasColumnType("text");

                    b.Property<bool>("Caregiver")
                        .HasColumnType("boolean");

                    b.Property<int?>("CaregiverId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CustomFieldsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("DoNotMail")
                        .HasColumnType("boolean");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("text");

                    b.Property<string>("Fax")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GenderCode")
                        .HasColumnType("text");

                    b.Property<string>("GuardianJson")
                        .HasColumnType("text");

                    b.Property<string>("HeightUnit")
                        .HasColumnType("text");

                    b.Property<double?>("HeightValue")
                        .HasColumnType("double precision");

                    b.Property<long?>("ImportId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImportPatientId")
                        .HasColumnType("text");

                    b.Property<string>("ImportSourceId")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ManagedMedicare")
                        .HasColumnType("boolean");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("Mrn")
                        .HasColumnType("text");

                    b.Property<string>("NativeLanguage")
                        .HasColumnType("text");

                    b.Property<string>("PhoneTypeToText")
                        .HasColumnType("text");

                    b.Property<string>("PhoneticName")
                        .HasColumnType("text");

                    b.Property<string>("PreferredName")
                        .HasColumnType("text");

                    b.Property<bool>("PrimaryDoNotEmail")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryEmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryInsuranceJson")
                        .HasColumnType("text");

                    b.Property<int?>("PrimarySiteId")
                        .HasColumnType("integer");

                    b.Property<string>("Race")
                        .HasColumnType("text");

                    b.Property<bool>("RecruitmentTextOptIn")
                        .HasColumnType("boolean");

                    b.Property<bool>("SecondaryDoNotEmail")
                        .HasColumnType("boolean");

                    b.Property<string>("SecondaryEmailAddress")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryInsuranceJson")
                        .HasColumnType("text");

                    b.Property<string>("Ssn")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid?>("Uid")
                        .HasColumnType("uuid");

                    b.Property<string>("WeightUnit")
                        .HasColumnType("text");

                    b.Property<double?>("WeightValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Zip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrimarySiteId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AllergyId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Reaction")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AllergyId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientAllergies");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeAtOnset")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientConditions");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientFamilyHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeAtOnset")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FamilyMemberId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("RelationName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("FamilyMemberId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientFamilyHistories");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientImmunization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImmunizationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ImmunizationTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImmunizationId");

                    b.HasIndex("ImmunizationTypeId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientImmunizations");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientMedicalDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientMedicalDevices");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Dosage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MedicationId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int?>("RouteId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RouteId");

                    b.ToTable("PatientMedications");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientMedicationCondition", b =>
                {
                    b.Property<int>("PatientMedicationId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientConditionId")
                        .HasColumnType("integer");

                    b.HasKey("PatientMedicationId", "PatientConditionId");

                    b.HasIndex("PatientConditionId");

                    b.ToTable("PatientMedicationConditions");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<bool>("OutOfService")
                        .HasColumnType("boolean");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("RawNumber")
                        .HasColumnType("text");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientPhones");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientProcedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("CptCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("ProcedureBy")
                        .HasColumnType("text");

                    b.Property<int?>("ProcedureId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("PatientProcedures");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProviderId");

                    b.ToTable("PatientProviders");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientSocialHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("SocialHistoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("SocialHistoryId");

                    b.ToTable("PatientSocialHistoryEntries");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CptCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProviderTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderTypeId");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.ProviderType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProviderTypes");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.SocialHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SocialHistories");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Patient", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Site", "PrimarySite")
                        .WithMany()
                        .HasForeignKey("PrimarySiteId");

                    b.Navigation("PrimarySite");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientAllergy", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Allergy", "Allergy")
                        .WithMany()
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Patient", "Patient")
                        .WithMany("Allergies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientCondition", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Patient", "Patient")
                        .WithMany("Conditions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientFamilyHistory", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Relation", "Relation")
                        .WithMany()
                        .HasForeignKey("FamilyMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Patient", "Patient")
                        .WithMany("FamilyHistory")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Patient");

                    b.Navigation("Relation");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientImmunization", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Immunization", "Immunization")
                        .WithMany()
                        .HasForeignKey("ImmunizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.ImmunizationType", "ImmunizationType")
                        .WithMany()
                        .HasForeignKey("ImmunizationTypeId");

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Patient", "Patient")
                        .WithMany("Immunizations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Immunization");

                    b.Navigation("ImmunizationType");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientMedicalDevice", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Patient", "Patient")
                        .WithMany("MedicalDevices")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientMedication", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Patient", "Patient")
                        .WithMany("Medications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.MedicationRoute", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId");

                    b.Navigation("Medication");

                    b.Navigation("Patient");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientMedicationCondition", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.PatientCondition", "PatientCondition")
                        .WithMany("MedicationConditions")
                        .HasForeignKey("PatientConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.PatientMedication", "PatientMedication")
                        .WithMany("MedicationConditions")
                        .HasForeignKey("PatientMedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientCondition");

                    b.Navigation("PatientMedication");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientPhone", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Patient", "Patient")
                        .WithMany("Phones")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientProcedure", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Patient", "Patient")
                        .WithMany("Procedures")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Procedure", "Procedure")
                        .WithMany()
                        .HasForeignKey("ProcedureId");

                    b.Navigation("Patient");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientProvider", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Patient", "Patient")
                        .WithMany("Providers")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientSocialHistoryEntry", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.Patient", "Patient")
                        .WithMany("SocialHistoryEntries")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.SocialHistory", "SocialHistory")
                        .WithMany()
                        .HasForeignKey("SocialHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("SocialHistory");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Provider", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.ProviderType", "ProviderType")
                        .WithMany()
                        .HasForeignKey("ProviderTypeId");

                    b.Navigation("ProviderType");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.SocialHistory", b =>
                {
                    b.HasOne("MockHealthSystem.Infrastructure.Data.Entities.ConditionType", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.Patient", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Conditions");

                    b.Navigation("FamilyHistory");

                    b.Navigation("Immunizations");

                    b.Navigation("MedicalDevices");

                    b.Navigation("Medications");

                    b.Navigation("Phones");

                    b.Navigation("Procedures");

                    b.Navigation("Providers");

                    b.Navigation("SocialHistoryEntries");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientCondition", b =>
                {
                    b.Navigation("MedicationConditions");
                });

            modelBuilder.Entity("MockHealthSystem.Infrastructure.Data.Entities.PatientMedication", b =>
                {
                    b.Navigation("MedicationConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
